config/routes.rb
Iotmarket::Application.routes.draw do
  get "omniauth_callbacks/facebook"

  resources :list_pins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users
  resources :users do
    resources :personal_infos
    resources :projects
  end

  get 'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/personal_info.rb
class PersonalInfo < ActiveRecord::Base
  attr_accessible :about, :age, :country, :name, :surname
  belongs_to :user, foreign_key: :user_id 
end

app/controllers/personal_infos_controller.rb
class PersonalInfosController < ApplicationController
  # GET /personal_infos
  # GET /personal_infos.json
  before_filter :identify , :except => [:new, :create, :edit, :update]
  before_filter :authenticate_user!
  skip_before_filter :admin, :except => :show
  
  def identify
    if current_user
      unless current_user.personal_info 
        @personal_info = current_user.build_personal_info
        render 'new' 
      end
    end
  end
  
  def index
    @user = User.find(params[:user_id])
    @personal_info = @user.personal_info
    @users_thought = @user.thoughts.order('rate desc').paginate(:page => params[:page])
    @users_quastions = @user.thoughts.paginate(:page => params[:page])
    @folowers = @user.folowers
    @folower = current_user.folowers.where(thinker_id: @user.id).first
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @personal_infos }
    end
  end

  # GET /personal_infos/1
  # GET /personal_infos/1.json
  def show
    @personal_info = current_user.personal_info
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @personal_info }
    end
  end

  # GET /personal_infos/new
  # GET /personal_infos/new.json
  def new
    @personal_info = current_user.build_personal_info

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @personal_info }
    end
  end

  # GET /personal_infos/1/edit
  def edit
    @personal_info = current_user.personal_info
  end

  # POST /personal_infos
  # POST /personal_infos.json
  def create
    @personal_info = current_user.create_personal_info(params[:personal_info])

    respond_to do |format|
      if @personal_info.save
        format.html { redirect_to user_path(current_user), notice: 'Personal info was successfully created.' }
        format.json { render json: @personal_info, status: :created, location: @personal_info }
      else
        format.html { render action: "new" }
        format.json { render json: @personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /personal_infos/1
  # PUT /personal_infos/1.json
  def update
    @personal_info = current_user.personal_info

    respond_to do |format|
      if @personal_info.update_attributes(params[:personal_info])
        format.html { redirect_to user_path(current_user), notice: 'Personal info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @personal_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_infos/1
  # DELETE /personal_infos/1.json
  def destroy
    @personal_info = current_user.personal_info
    @personal_info.destroy

    respond_to do |format|
      format.html { redirect_to personal_infos_url }
      format.json { head :no_content }
    end
  end
end

app/views/personal_infos/_form.html.haml
= form_for @personal_info, :url => user_personal_info_path(current_user), :html => {:multipart => true}  do |f|
  - if @personal_info.errors.any?
    #error_explanation
      %h2= "#{pluralize(@personal_info.errors.count, "error")} prohibited this personal_info from being saved:"
      %ul
        - @personal_info.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :surname
    = f.text_field :surname
  .field
    = f.label :age
    = f.number_field :age
  .field
    = f.label :image
    image_tag(@personal_info.image.thumb.url) if @personal_info.image?
    f.file_field :image
    f.hidden_field :image_cache
  .field
    = f.label :country
    = f.text_field :country
    = f.label :about
    = f.text_field :about
  .actions
    = f.submit 'Save'

app/views/personal_infos/edit.html.haml
.row-fluid
  .span5.offset4.box-shadow
    %h1 Editing personal information
    = render 'form'
    = link_to 'Back', user_path(current_user)

app/views/personal_infos/new.html.haml
.row-fluid
  .span4.offset4.box-shadow
    %h2.shadow1.sansation1 Please, input your personal information
    = form_for @personal_info, :url =>  user_personal_infos_path(current_user), :html => {:multipart => true, :method => :post}  do |f|
      - if @personal_info.errors.any?
        #error_explanation
          %h2= "#{pluralize(@personal_info.errors.count, "error")} prohibited this personal_info from being saved:"
          %ul
            - @personal_info.errors.full_messages.each do |msg|
              %li= msg

      = f.text_field :name, :placeholder => "Name"
      = f.text_field :surname, :placeholder => "Surname"
      = f.number_field :age, :placeholder => "Age"
      .field
        it's okay
        image_tag(@personal_info.image.thumb.url) if @personal_info.image?
        f.file_field :image, :placeholder => "Photo"
        f.hidden_field :image_cache
      = f.text_field :country, :placeholder => "Country"
      = f.text_field :about, :placeholder => "About you"
      .actions
        %button.btn.btn-primary{ :type => "submit" } Save

    = link_to 'Back', user_personal_infos_path(current_user)

app/views/personal_infos/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @personal_info.name
%p
  %b Surname:
  = @personal_info.surname
%p
  %b Gender:
  = @personal_info.gender
%p
  %b Age:
  = @personal_info.age
%p
  %b Image:
  = @personal_info.image
%p
  %b Country:
  = @personal_info.country
%p
  %b Marital status:
  = @personal_info.marital_status
%p
  %b Credo:
  = @personal_info.credo
%p
  %b Religion:
  = @personal_info.religion
%p
  %b Political views:
  = @personal_info.political_views
%p
  %b Smf more:
  = @personal_info.smf_more

= link_to 'Edit', edit_personal_info_path(@personal_info)
\|
= link_to 'Back', personal_infos_path