config/routes.rb
Iotmarket::Application.routes.draw do
  get "omniauth_callbacks/facebook"

  resources :list_pins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users
  resources :users do
    resources :personal_infos
    resources :projects
  end

  get 'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  has_one :personal_info, foreign_key: :user_id, dependent: :destroy
  has_many :projects, foreign_key: :user_id
  devise :omniauthable, :omniauth_providers => [:facebook]
  devise :database_authenticatable, :registerable, #:recoverable,
          :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  attr_accessible :provider, :uid
    def self.find_for_facebook_oauth( auth, signed_in_resource= nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name: auth.extra.raw_info.name, provider: auth.provider, uid: auth.uid, email: auth.info.email, password: Devise.friendly_token[0,20])
    end
    user     
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
	user.email = data["email"] if user.email.blank?
      end
    end
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end     
  end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  
  
  
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @personal_info = @user.personal_info
    @projects = @user.projects.paginate(:page => params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :provider
    = f.text_field :provider
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Username
    %th Provider
    %th Url
    %th
    %th
    %th
    %th link

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.provider
      %td= user.uid
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %td= link_to 'link', user_path(user)
%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
.row-fluid
  .span4.box-shadow
    -if @user
      %ul.thumbnails
        %li.span12
          - if @personal_info 
            if @personal_info.image
            .thumbnail
              .img-polaroid
                image_tag(@personal_info.image)    
            %dl.dl-horizontal
              - unless @personal_info.name == ""
                %dt Name:
                %dd= @personal_info.name
              - unless @personal_info.surname == ""
                %dt Surname:
                %dd= @personal_info.surname
              - unless @personal_info.age == nil
                %dt Age:
                %dd= @personal_info.age
              - unless @personal_info.country == ""
                %dt Country:
                %dd= @personal_info.country
              - unless @personal_info.about == ""
                %dt Whatever about you:
                %dd= @personal_info.about

      - if current_user == @user
        - if @personal_info
          %a{:href =>"#{edit_user_personal_info_path(current_user, @personal_info)}", :style => "background-color: inherit; color: inherit"} Edit 
        - else
          %a{:href =>"#{new_user_personal_info_path(current_user, @personal_info)}", :style => "background-color: inherit; color: inherit"} Add personall info
      %a{:href =>"#{users_path}", :style => "background-color: inherit; color: inherit"} Back
      
      - unless @user == current_user
        - if @personal_info
          - if @user.id = 100000
            %a{:href =>"#", :style => "background-color: inherit; color: inherit", 'data-method' => 'post'} Follow
          - else
            %a{:href =>"#", :style => "background-color: inherit; color: inherit", 'data-method' => 'delete'} Unfollow
  .span8
    -if @user == current_user
      %strong= link_to 'Create new project', new_user_project_path(current_user)
    .tabbables.tabs-right
      %ul.nav.nav-tabs
        %li.active
          %a{"data-toggle" => "tab", :href => "#tab1"} 
            .shadow Projects
        %li
          %a{"data-toggle" => "tab", :href => "#tab2"}
            .shadow Interesting projects
        %li
          %a{"data-toggle" => "tab", :href => "#tab3"} 
            .shadow Friends
      .tab-content
        #tab1.tab-pane.active
          - @projects.each do |project| 
            %h2
              %a{:href =>"#{user_project_path(project)}", :style => "background-color: inherit;"} #{'project.name'}
            %blockquote
              %strong= project.description
              %h4 project.rate
          %hr.featurette-divider 
          = will_paginate @projects
        #tab2.tab-pane
          @interesting_projects.each do |interesting_project|           
          %h2
            %a{:href =>"", :style => "background-color: inherit;"} #{'interesting_project.name'} 
          %blockquote
            %strong interesting_project.description
            %h4 interesting_project.rate
          %hr.featurette-divider   
        #tab3.tab-pane
          @folowers.each do |folower|
          @friend = User.find(folower.thinker_id)
          if @friend
          if @friend.personal_info
          .featurette
            %em.lead
              %a{:href =>"#", :style => "background-color: inherit; color: inherit"} #{'@friend.personal_info.name'}  
          %hr.featurette-divider