config/routes.rb
Iotmarket::Application.routes.draw do
  get "omniauth_callbacks/facebook"

  resources :list_pins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :users
  resources :users do
    resources :personal_infos
    resources :projects
  end

  get 'about' => 'pages#about'

  root :to => 'pages#home'

end

app/models/list_pin.rb
class ListPin < ActiveRecord::Base
  attr_accessible :description
end

app/controllers/list_pins_controller.rb
class ListPinsController < ApplicationController
  # GET /list_pins
  # GET /list_pins.json
  def index
    @list_pins = ListPin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @list_pins }
    end
  end

  # GET /list_pins/1
  # GET /list_pins/1.json
  def show
    @list_pin = ListPin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list_pin }
    end
  end

  # GET /list_pins/new
  # GET /list_pins/new.json
  def new
    @list_pin = ListPin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list_pin }
    end
  end

  # GET /list_pins/1/edit
  def edit
    @list_pin = ListPin.find(params[:id])
  end

  # POST /list_pins
  # POST /list_pins.json
  def create
    @list_pin = ListPin.new(params[:list_pin])

    respond_to do |format|
      if @list_pin.save
        format.html { redirect_to @list_pin, notice: 'List pin was successfully created.' }
        format.json { render json: @list_pin, status: :created, location: @list_pin }
      else
        format.html { render action: "new" }
        format.json { render json: @list_pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /list_pins/1
  # PUT /list_pins/1.json
  def update
    @list_pin = ListPin.find(params[:id])

    respond_to do |format|
      if @list_pin.update_attributes(params[:list_pin])
        format.html { redirect_to @list_pin, notice: 'List pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list_pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_pins/1
  # DELETE /list_pins/1.json
  def destroy
    @list_pin = ListPin.find(params[:id])
    @list_pin.destroy

    respond_to do |format|
      format.html { redirect_to list_pins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/list_pins_helper.rb
module ListPinsHelper
end

app/views/list_pins/_form.html.erb
<%= simple_form_for(@list_pin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/list_pins/edit.html.erb
<h1>Editing list_pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @list_pin %> |
<%= link_to 'Back', list_pins_path %>

app/views/list_pins/index.html.erb
<h1>Listing list_pins</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @list_pins.each do |list_pin| %>
  <tr>
    <td><%= list_pin.description %></td>
    <td><%= link_to 'Show', list_pin %></td>
    <td><%= link_to 'Edit', edit_list_pin_path(list_pin) %></td>
    <td><%= link_to 'Destroy', list_pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New List pin', new_list_pin_path %>

app/views/list_pins/new.html.erb
<h1>New list_pin</h1>

<%= render 'form' %>

<%= link_to 'Back', list_pins_path %>

app/views/list_pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @list_pin.description %>
</p>


<%= link_to 'Edit', edit_list_pin_path(@list_pin) %> |
<%= link_to 'Back', list_pins_path %>